version: "3.1"
services:
    api:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - "8000:80"
        depends_on:
            - db
    db:
        container_name: mysql
        image: mysql
        environment:
            MYSQL_DATABASE: Hexagonal
            MYSQL_USER: sa
            MYSQL_PASSWORD: MyPassword001
            MYSQL_ROOT_PASSWORD: root
        volumes:
            - ./migrations:/docker-entrypoint-initdb.d
    adminer:
        image: adminer
        ports:
            - "8080:8080"
        depends_on:
            - db